name: twooter_dart
description: The unofficial Twooter client for Dart!
version: 1.0.0
homepage: https://github.com/IncognitoJam/twooter_dart
author: Cameron Clough <cameronjclough@gmail.com>

environment:
  sdk: '>=2.2.0 <3.0.0'

dependencies:
  dio: 2.1.7

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
